# Generated by Django 5.2.7 on 2025-11-12 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='workers/')),
                ('contacts', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='auction_items/')),
                ('type', models.CharField(choices=[('painting', 'Painting'), ('porcelain', 'Porcelain'), ('jewelry', 'Jewelry')])),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auction_end_time', models.DateTimeField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_items', to='main.worker')),
            ],
        ),
    ]
