# Generated by Django 5.2.7 on 2025-11-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
